apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keycloak
  description: Open Source Identity and Access Management
  tags:
    - java
  links:
    - url: https://www.keycloak.org/
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: guests
